# Site settings
name: Bennett Oh
title: Bennett Oh | Aspiring Software Developer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://bennettoh.github.io/
baseurl: https://bennettoh.github.io/
email: bennettoh.dev@gmail.com
cover: https://bennettoh.github.io/img/og.png
logo: https://bennettoh.github.io/img/emojis/technologist.png
resume: https://bennettoh.github.io/img/Resume 2020 Bennett Oh.pdf
social:
  - title: email
    url: mailto:bennettoh.dev@gmail.com
  - title: instagram
    url: https://instagram.com/bennett.oh
  - title: github
    url: https://github.com/bennettoh
  - title: linkedin
    url: https://www.linkedin.com/in/bennett-oh

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
